name: Run Poster Generate

#on:
#  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"
on:
  workflow_dispatch:
    inputs:
      time:
        description: 'time list'
        required: false
      value:
        description: 'value list'
        required: false
  pull_request:
  
env:
  # please change to your own config.
  # this actions generate only this year
  # If you fork this please change the type to yours below
  TYPE: "apple_health" # support strava/gpx/ns/cichang/shanbay/duolingo/issue/leetcode/twitter/github/gitlab/kindle/bilibili/wakatime/dota2/forest, Please change the 'pass' it to your own separated by commas
  ME: whrsss
  # change env here
  GITHUB_NAME: whrsss
  GITHUB_EMAIL: 1593774151@qq.com
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # from https://github.com/pdm-project/pdm/blob/main/.github/workflows/ci.yml
      - name: Set Variables
        id: set_variables
        shell: bash
        run: |
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: ${{ runner.os }}-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Run sync apple_health script
        if: contains(env.TYPE, 'apple_health')
        run: |
#          python3 -m github_poster apple_health --apple_health_mode incremental --apple_health_date ${{ github.event.inputs.time }} --apple_health_value ${{ github.event.inputs.value }} --year 2020-2023 --apple_health_record_type move --me "whrsss"
          python3 -m github_poster apple_health --apple_health_mode incremental --dates ${{ github.event.inputs.time }} --values ${{ github.event.inputs.value }} --year 2020-2023 --apple_health_record_type move --me "whrsss"

#      - name: Mv svg files to examples
#        # only for me to show
#        if: github.repository_owner == 'whrsss'
#        run: mv OUT_FOLDER/*.svg examples/

      - name: Push new poster
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m 'update new poster' || echo "nothing to commit"
          git push || echo "nothing to push"
