name: Run Poster Generate

on:
  workflow_dispatch:
    inputs:
      time:
        description: 'time str'
        required: false
      value:
        description: 'value str'
        required: false
  
env:
  TYPE: "AppleHealthData"
  ME: whrsss
  # change env here
  GITHUB_NAME: whrsss
  GITHUB_EMAIL: 1593774151@qq.com
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Variables
        id: set_variables
        shell: bash
        run: |
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache PIP
        uses: actions/cache@v3
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: ${{ runner.os }}-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run sync AppleHealthData script
        if: contains(env.TYPE, 'AppleHealthData')
        run: |
          python3 -m github_poster AppleHealthData --apple_health_mode incremental --dates $'${{ github.event.inputs.time }}' --values  $'${{ github.event.inputs.value }}' --year 2020-2024 --apple_health_record_type move --me "了迹奇有没"

      - name: Push new poster
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m 'update new poster' || echo "nothing to commit"
          git push || echo "nothing to push"